// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  /* static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDF9mzYdQIZdiKKiT5TwHPpZ7O9zv0ugoA",
      authDomain: "file-management-886dc.firebaseapp.com",
      projectId: "file-management-886dc",
      storageBucket: "file-management-886dc.appspot.com",
      messagingSenderId: "519579716174",
      appId: "1:519579716174:web:bd23769abbcfec05fb111f",
      measurementId: "G-0CC3SPSDQH"); */

  /* static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB3MTdro0anCZ0H4Ogu8C0ATB_iSqXrpeI",
      authDomain: "customer-portal-fac87.firebaseapp.com",
      projectId: "customer-portal-fac87",
      storageBucket: "customer-portal-fac87.appspot.com",
      messagingSenderId: "48473023840",
      appId: "1:48473023840:web:6d67d22298a6843de36a05",
      measurementId: "G-D2VZD6PVTM"); */

   static const FirebaseOptions web = FirebaseOptions{
  apiKey: "AIzaSyCbgse8BYuJETrfby6cBdC8RwHACZ6fg54",
  authDomain: "surya-photography.firebaseapp.com",
  projectId: "surya-photography",
  storageBucket: "surya-photography.appspot.com",
  messagingSenderId: "581342665361",
  appId: "1:581342665361:web:22db0ebd5244bbd719bd30",
  measurementId: "G-BFRXWP9KDQ"
};
}
